### ISSUE TITLE
Problem with Trackpad 

### ISSUE THREAD

**Issue by darktime78** [Jarvay/Acer-Swift3-SF313-52#10]
Hi, I used your config and installed big sur on my laptop sf313-52g. I have problems with the buttons on my trackpad. The right click does not work, and the left one does not work well. What is the problem?

**Comment by Jarvay** [comment]
It seems the physical right button not works.
I prefer using those settings.
![image](https://user-images.githubusercontent.com/16760347/154187847-a061e99c-58a3-49c8-965b-579581797c12.png)

**Comment by darktime78** [comment]
Thanks, OK.
