### ISSUE TITLE
安装上了有如下问题

### ISSUE THREAD

**Issue by shihengs** [Jarvay/Acer-Swift3-SF313-52#3]
1，检测不到声卡
2，检测不到无线网卡，但是可以驱动蓝牙
3，睡眠就醒不过来
第三个问题不重要，请问前两个问题怎么解决？

**Comment by shihengs** [comment]
MscOS版本为10.15.7

**Comment by Jarvay** [comment]
1.声卡如果是使用我的版本的话id是23，未提交合并请求到原仓库
2.需要换为catalina的wifi驱动
3.我这睡眠是正常的
