### ISSUE TITLE
安装了Monterey但是没有声音

### ISSUE THREAD

**Issue by shihengs** [Jarvay/Acer-Swift3-SF313-52#4]
请问声卡的id还是23吗？在设备属性DP中增加了alc-layout-id Data 17000000，在NVRAM变量中boot-args中增加了alcid=23，依然没有声音，求助！谢谢！

**Comment by Jarvay** [comment]
抱歉，上班没用过扬声器和耳机，不知道有问题，已更新，不需要额外设置
