### ISSUE TITLE
开启HIDPI失败

### ISSUE THREAD

**Issue by shihengs** [Jarvay/Acer-Swift3-SF313-52#6]
按照您提供的脚本，通过远程模式尝试，选择分辨率手工输入：2256x1504，中间的x是英文字母x，不是*，可以正常启动，但启动后还是和原来一样，没有任何变化。把您更新的EFI导入U盘，正常启动也有声音了，感谢！
操作HIDPI脚本时，也是用的U盘启动，不知道是否和这个有关系，还请指导，谢谢！

**Comment by Jarvay** [comment]
分辨率输入可以参考我用的:1920x1280 1650x1100 1380x920 1280x854
重启后在设置-显示器里切换缩放应该就能生效

**Comment by shihengs** [comment]
用您给的分辨率建议，修改成功了，非常感谢！不过我犯了一个错误，因为我还没有学会禁用CFG Lock，电脑长时间无操作进入了睡眠，而且无法唤醒，我只好长按电源键关机，结果BIOS被初始化了，我忘记了用什么快捷键将被锁定的SATA Mode激活（原来的笔记怎么也找不到了），能麻烦您告诉我一下吗？谢谢！现在是Optane without RAID，Windows和MacOS都无法进入了，求救！

**Comment by shihengs** [comment]
我找到了快捷键，是在Main选项卡上按Ctrl+S，谢谢！另外想试试禁用CFG Lock，您的帖子里提到的DVMT Pre-Allocated ，是否也会影响睡眠唤醒功能？还是仅仅是外接显示器时能输出4K+60Hz？

**Comment by shihengs** [comment]
按照说明和相关教程成功开启Hidpi，谢谢！
