### ISSUE TITLE
AppleALC 1.6.6 更新

### ISSUE THREAD

**Issue by David1007587693** [Jarvay/Acer-Swift3-SF313-52#8]
Added Conexant CX11970 (CX8400) layout-id 13 for Acer Swift 3 SF31* (Ice Lake) by m0d16l14n1

**Comment by Jarvay** [comment]
如果希望跟随官方AppleALC可以直接使用官方的，但是如果使用HDMI需要在声卡的Device-Properties添加No-gfx-hda，参考https://github.com/m0d16l14n1/icelake-hackintosh
